### PR TITLE
Update class-woocommerce-email-validation.php

### PR DESCRIPTION
**Pull request by ablears**
Fixed issue #6 - email won't validate in Woo 3.0

### CODE REVIEW

**Comment by gwegner** [comment]
Awesome @ablears - works like a charm! Hope the author will release an official update soon!

**Comment by NGiacopuzzi** [comment]
Awesome. Thank you!

**Comment by jonasskafte** [comment]
Thanks!

**Comment by prikhi** [comment]
@ablears FYI, you made this as a PR to your fork, I'm guessing you wanted it as a PR to @hlashbrooke's repo

**Comment by ablears** [comment]
Oops @prikhi. Thanks for pointing that out :)

**Pull request merged**
